import * as fs from "node:fs";
import * as path from "node:path";
import type { ParseResult } from "@alcyone-labs/arg-parser";

/**
 * Test utilities for DxtGenerator
 * Contains methods that are only used during testing
 */
export class DxtGeneratorTestUtils {
  private argParserInstance: any;
  private extractMcpServerInfo: () => any;
  private handleExit: (
    exitCode: number,
    message?: string,
    type?: ParseResult["type"],
    data?: any,
  ) => ParseResult | never;

  constructor(
    argParserInstance: any,
    extractMcpServerInfo: () => any,
    handleExit: (
      exitCode: number,
      message?: string,
      type?: ParseResult["type"],
      data?: any,
    ) => ParseResult | never,
  ) {
    this.argParserInstance = argParserInstance;
    this.extractMcpServerInfo = extractMcpServerInfo;
    this.handleExit = handleExit;
  }

  /**
   * Handles DXT generation in test mode by creating mock DXT package structure
   */
  public async handleTestModeDxtGeneration(
    processArgs: string[],
    buildDxtIndex: number,
  ): Promise<ParseResult> {
    try {
      const outputDir = processArgs[buildDxtIndex + 1] || "./dxt-packages";

      const mcpTools = this.argParserInstance.toMcpTools ? this.argParserInstance.toMcpTools() : [];
      if (mcpTools.length === 0) {
        return this.handleExit(0, "No MCP servers found", "success");
      }

      const serverInfo = this.extractMcpServerInfo();

      const folderName = `${serverInfo.name.replace(/[^a-zA-Z0-9_-]/g, "_")}-dxt`;
      const buildDir = path.join(outputDir, folderName);

      if (!fs.existsSync(buildDir)) {
        fs.mkdirSync(buildDir, { recursive: true });
      }

      const manifest = {
        dxt_version: "0.1",
        name: serverInfo.name,
        version: serverInfo.version,
        description: serverInfo.description,
        author: serverInfo.author,
        server: {
          type: "node",
          entry_point: "server/index.mjs",
          mcp_config: {
            command: "node",
            args: ["${__dirname}/server/index.mjs", "--s-mcp-serve"],
            env: {},
          },
        },
        tools: mcpTools.map((tool: any) => ({
          name: tool.name,
          description: tool.description,
        })),
        icon: "logo.jpg",
      };

      fs.writeFileSync(path.join(buildDir, "manifest.json"), JSON.stringify(manifest, null, 2));

      const packageJson = {
        name: serverInfo.name,
        version: serverInfo.version,
        description: serverInfo.description,
        main: "index.mjs",
        type: "module",
      };
      fs.writeFileSync(path.join(buildDir, "package.json"), JSON.stringify(packageJson, null, 2));

      const readme = `# ${serverInfo.name}

${serverInfo.description}

Generated by @alcyone-labs/arg-parser`;
      fs.writeFileSync(path.join(buildDir, "README.md"), readme);

      const buildScript = `#!/bin/bash
echo "Mock DXT build script for ${serverInfo.name}"`;
      fs.writeFileSync(path.join(buildDir, "build-dxt-package.sh"), buildScript);

      return this.handleExit(0, "DXT package generation completed", "success", {
        entryPoint: "test-mode",
        outputDir: buildDir,
      });
    } catch (error) {
      return this.handleExit(
        1,
        `Test mode DXT generation failed: ${error instanceof Error ? error.message : String(error)}`,
        "error",
      );
    }
  }

  /**
   * Checks if the current environment is in test mode
   */
  public static isTestMode(): boolean {
    return (
      process.env["NODE_ENV"] === "test" ||
      process.argv[0]?.includes("vitest") ||
      process.argv[1]?.includes("vitest") ||
      process.argv[1]?.includes("tinypool")
    );
  }
}
